### PR TITLE
Devel/world of boxes

### PR DESCRIPTION
**Pull request by giulioturrisi**
This PR introduces random terrain generation. Things to fix:

- [x] random generation only happens at runtime. This should be likely happen at reset too
- [x] rotation in terrain.py does not use yet scipy Rotation

### CODE REVIEW

**Comment by Danfoa** [comment]
Hi @giulioturrisi, 

I think if we generate a large enough random terrain, at reset time we can simply change the base x,y position to set it to a different random part of the already random terrain. But we could also trigger terrain resets.

**Comment by giulioturrisi** [comment]
@git-gfischer can you look at fixing the random reset (first box in my first comment)? We should have random terrain at every reset, not only at startup

**Comment by giulioturrisi** [comment]
an additional task is to avoid to save a new scene if random_boxes or random_pyramids is chosen. This can be done by calling mujoco.MjModel.from_xml_string. The problem is that if i convert the scene scene_flat.xml to string after adding the random element, aliengo_xml (or in general, any robot.xml) is defined there as "include" and not directly loaded inside.

**Comment by giulioturrisi** [comment]
adding: i noticed that on reset some collisions remains with the old boxes even if they are not anymore displayed. I'm wondering what this could be, we only update mjmodel and not mjdata, this could be the cause of it. But if we do update mjdata too, the robot became a ghost.

**Comment by giulioturrisi** [comment]
In the latest commit, we solve the problem with ghost geom by instantiating a new viewer when mjmodel and mjdata are changed. This Is not really ideal and ugly, since a new screen will be spawned and the old one is closed. Plus, the drawing routing of the grf, swing, etc, I
Is broken.  I'm asking to the discord group If there Is another way, but i think there Is not. Can you @Danfoa have a look at the drawing problem? There could be something else that broke, like your Ghost stuff

**Comment by giulioturrisi** [comment]
Notice that this problem can be actually bypassed for now, if we perform randlmization at the env level (creating a new env) rather than inside It. So yes, i would say let's skip It for now.

**Comment by giulioturrisi** [comment]
To close this pull request, @git-gfischer and me need to perform a better reset function. We can randomize the position of the robot (x-y), making the robot pointing always towards the center of the spawned area (that for now will remain the same)

**Comment by giulioturrisi** [comment]
I agree. I'm taking for granted that if the user chooses random terrain, he will know that there is an inherent randomicity. We should setup static environment for the other cases.

**Comment by giulioturrisi** [comment]
The pull request is now complete. Please @Danfoa, have a look at it

**Pull request merged**
